- hosts: DC2_FABRIC

  tasks:

    - name: include global_vars
      tags: [build, provision]
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/AVD_LAB.yml"
        - "../global_vars/EOS.yml"

    - name: generate intented variables
      import_role:
         name: arista.avd.eos_l3ls_evpn
      tags: [build]

    - name: update with dci information
      import_role:
         name: eos_dci
      tags: [build]

    - name: generate device intended config and documention
      import_role:
         name: arista.avd.eos_cli_config_gen
      tags: [build]

    - name: deploy configuration to device
      import_role:
         name: arista.avd.eos_config_deploy_eapi

    - name: Force replace configuration with intended configuration
      eos_config:
        src: "{{root_dir}}/intended/configs/{{ inventory_hostname }}.cfg"
        replace: config
        save_when: modified
      tags: [provision]

    - name: backup configuration
      eos_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_running-config.conf"
          dir_path: "{{ root_dir }}/config_backup/"
      tags: [provision]

    # - name: validate states on EOS devices
    #   import_role:
    #      name: arista.avd.eos_validate_state